package dev.easyide.app.ui.screens.workspace.edit

/**
 * The subset of a VS Code `language-configuration.json` the editor acts on.
 *
 * Pure data with no Android types, so the edit rules that read it run in plain
 * JVM tests. Bundled configs are generated by `tools/build-grammars.py`, which
 * normalises pairs to objects and regexes to `{pattern, flags}`.
 */
data class LanguageConfig(
    val lineComment: String? = null,
    val blockComment: Pair<String, String>? = null,
    val brackets: List<CharPair> = emptyList(),
    val autoClosingPairs: List<CharPair> = emptyList(),
    val surroundingPairs: List<CharPair> = emptyList(),
    /** Characters after the caret that still allow auto-closing; VS Code's default when absent. */
    val autoCloseBefore: String = DEFAULT_AUTO_CLOSE_BEFORE,
    val increaseIndent: Regex? = null,
    val decreaseIndent: Regex? = null,
    val onEnterRules: List<EnterRule> = emptyList(),
) {
    companion object {
        /** VS Code's `autoCloseBefore` default for languages that do not set one. */
        const val DEFAULT_AUTO_CLOSE_BEFORE = ";:.,=}])> \n\t"

        private val BRACKETS = listOf(CharPair("(", ")"), CharPair("[", "]"), CharPair("{", "}"))

        /**
         * For the grammars VS Code ships no config for: brackets and quotes
         * behave, comment toggling is a no-op because the token is unknown.
         */
        val GENERIC = LanguageConfig(
            brackets = BRACKETS,
            autoClosingPairs = BRACKETS + listOf(
                CharPair("\"", "\"", setOf(SCOPE_STRING)),
                CharPair("'", "'", setOf(SCOPE_STRING, SCOPE_COMMENT)),
            ),
            surroundingPairs = BRACKETS + listOf(CharPair("\"", "\""), CharPair("'", "'")),
        )
    }
}

data class CharPair(val open: String, val close: String, val notIn: Set<String> = emptySet())

/** VS Code `IndentAction`. */
enum class IndentAction { NONE, INDENT, INDENT_OUTDENT, OUTDENT }

class EnterRule(
    val beforeText: Regex,
    val afterText: Regex? = null,
    val previousLineText: Regex? = null,
    val indent: IndentAction = IndentAction.NONE,
    val appendText: String = "",
    val removeText: Int = 0,
)

/** `notIn` scope names used by language configurations. */
const val SCOPE_STRING = "string"
const val SCOPE_COMMENT = "comment"

/**
 * Compiles a JavaScript regex from a language configuration for the JVM.
 *
 * JS accepts two things `java.util.regex` rejects and the bundled configs use
 * both: a literal `{` that is not a quantifier (C, Go, LaTeX, JSON rules), and
 * Unicode property names like `\p{Alphabetic}` (Markdown's word pattern).
 * Returns null for anything still invalid so one bad rule drops alone.
 */
fun compileJsRegex(pattern: String, flags: String): Regex? {
    val options = if ('i' in flags) setOf(RegexOption.IGNORE_CASE) else emptySet()
    return runCatching { Regex(translateJsRegex(pattern), options) }.getOrNull()
}

private val JS_PROPERTY_NAMES = mapOf(
    "Alphabetic" to "IsAlphabetic",
    "Number" to "N",
    "Nonspacing_Mark" to "Mn",
    "Letter" to "L",
)

// The closing brace is escaped on purpose: java.util.regex tolerates a bare `}`, but Android's
// regex engine rejects it, and this is a top-level constant, so a failure here disables every
// language configuration at class initialisation instead of dropping one rule.
private val QUANTIFIER = Regex("""\{\d+(,\d*)?\}""")

internal fun translateJsRegex(pattern: String): String {
    val out = StringBuilder(pattern.length + 8)
    var i = 0
    var inClass = false
    while (i < pattern.length) {
        val c = pattern[i]
        when {
            c == '\\' && i + 1 < pattern.length -> {
                val next = pattern[i + 1]
                val close = pattern.indexOf('}', i)
                if ((next == 'p' || next == 'P') && i + 2 < pattern.length && pattern[i + 2] == '{' && close > 0) {
                    val name = pattern.substring(i + 3, close)
                    out.append('\\').append(next).append('{').append(JS_PROPERTY_NAMES[name] ?: name).append('}')
                    i = close + 1
                    continue
                }
                out.append(c).append(next)
                i += 2
                continue
            }
            inClass -> {
                if (c == ']') inClass = false
                out.append(c)
            }
            c == '[' -> {
                inClass = true
                out.append(c)
                // A leading `]` (or `^]`) is literal in both dialects.
                if (pattern.startsWith("^]", i + 1)) { out.append("^]"); i += 2 }
                else if (pattern.startsWith("]", i + 1)) { out.append(']'); i += 1 }
            }
            c == '{' && QUANTIFIER.matchAt(pattern, i) == null -> out.append("\\{")
            else -> out.append(c)
        }
        i++
    }
    return out.toString()
}
