#!/usr/bin/env node
// build-matrix.mjs - joins VS Code data, corpus usage, our-code inventory and the hand-maintained mapping
// (tools/vsx-audit/mapping/*.json) into docs/vsx-compat/matrix/*.md and docs/vsx-compat/data/matrix-summary.json.
// Zero dependencies, deterministic (no clock, stable sorts). Usage: node tools/vsx-audit/build-matrix.mjs
//
// API id normalisation / noise filter (documented in mapping/api-rules.json _doc):
//   1. strip a leading `default.` (ESM interop `vscode.default.X`);
//   2. `<stableNonNamespaceId>.<member>` (e.g. `version.split`) folds into the stable id;
//   3. drop ids matching /^[A-Z][A-Z0-9_]*$/ that are not stable ids, and bare lower-case identifiers that are not
//      stable ids and match no fork rule (length, slice, indexOf, message ...): extractor noise.
//   Non-stable ids whose rule maps to a track-"in" capability are re-classed proposed.api (OOS-PROP).
// E_in: mirror of render-corpus.mjs classify() (D7 rule, corpus.md §2) - keep the two in sync.
// Priority = weightShare over E_in (share of E_in download weight whose extensions use the row), ties by #extensions.
// Milestone coverage: an E_in extension is covered at Mk when every in-scope (track "in") API capability,
// contribution point and menu location it uses has milestone <= Mk (plus host + manifest at M1); OOS-track items are
// excluded (scored per track, D7/D8). Gate g4 scenarios and bugs are not modelled: projected scores are upper bounds.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DATA = path.join(ROOT, 'docs/vsx-compat/data');
const MAP = path.join(ROOT, 'tools/vsx-audit/mapping');
const OUT = path.join(ROOT, 'docs/vsx-compat/matrix');
const rd = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const vApi = rd(path.join(DATA, 'vscode-api.json')), vCon = rd(path.join(DATA, 'vscode-contributes.json'));
const vAct = rd(path.join(DATA, 'vscode-activation-events.json')), vWhen = rd(path.join(DATA, 'vscode-when-context.json'));
const vMenu = rd(path.join(DATA, 'vscode-menus.json')), vShape = rd(path.join(DATA, 'vscode-exthost-shapes.json'));
const usage = rd(path.join(DATA, 'corpus-usage.json')), corpus = rd(path.join(DATA, 'corpus.json'));
const caps = rd(path.join(MAP, 'capabilities.json')).capabilities;
const rules = rd(path.join(MAP, 'api-rules.json')).rules.map(([p, c]) => [new RegExp(p), c]);
const mCon = rd(path.join(MAP, 'contributes.json')), mAct = rd(path.join(MAP, 'activation.json')).events;
const mMenu = rd(path.join(MAP, 'menus.json')), mWhen = rd(path.join(MAP, 'when.json')).rules, mShape = rd(path.join(MAP, 'shapes.json')).shapes;
const MAX = 580;
const SRC = 'docs/vsx-compat/data/{vscode-*,corpus,corpus-usage,ourcode-*}.json and tools/vsx-audit/mapping/*.json';
const HDR = (t) => [`# ${t}`, '', `Generated by tools/vsx-audit/build-matrix.mjs from ${SRC} — do not edit by hand.`, `VS Code ${vApi.meta.vscodeVersion} (${vApi.meta.vscodeCommit.slice(0, 7)}); corpus snapshot ${corpus.meta.snapshotAt} (scanVersion ${corpus.meta.scanVersion}). How to read: [../gap-analysis.md](../gap-analysis.md).`, ''];

// ---------- corpus, E_in ----------
const NB_ONLY = new Set(['notebookRenderer', 'notebookPreload', 'notebooks']);
const CHAT_KEYS = new Set(['chatParticipants', 'languageModelTools', 'chatSkills', 'chatInstructions', 'chatContext', 'mcpServerDefinitionProviders', 'languageModelToolSets']);
function classify(e) {
  if (e.noGlibcArm64) return 'platform-unavailable';
  const extraViewKeys = Object.keys(e.views || {}).filter((k) => k !== 'webviewViews');
  if ((e.debuggers || 0) > 0 && (e.languages || 0) === 0 && extraViewKeys.length === 0 && (e.views?.webviewViews || 0) === 0 && (e.notebooks || 0) === 0) return 'oos:DAP';
  const ck = Object.keys(e.contributes || {});
  if (ck.length && ck.every((k) => NB_ONLY.has(k))) return 'oos:NB';
  if (ck.length && ck.every((k) => CHAT_KEYS.has(k))) return 'oos:CHAT';
  return 'in';
}
const EXT = new Map(corpus.extensions.map((e) => [e.id, e]));
const TOTAL = corpus.extensions.reduce((s, e) => s + e.downloadCount, 0);
const EIN = new Set(corpus.extensions.filter((e) => classify(e) === 'in').map((e) => e.id));
const TOTAL_IN = [...EIN].reduce((s, id) => s + EXT.get(id).downloadCount, 0);
const wAll = (ids) => [...ids].reduce((s, id) => s + (EXT.get(id)?.downloadCount || 0), 0) / TOTAL;
const wIn = (ids) => [...ids].filter((id) => EIN.has(id)).reduce((s, id) => s + EXT.get(id).downloadCount, 0) / TOTAL_IN;
const top3 = (ids) => [...ids].sort((a, b) => (EXT.get(b)?.downloadCount || 0) - (EXT.get(a)?.downloadCount || 0) || a.localeCompare(b)).slice(0, 3).join(', ');

// ---------- formatting ----------
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const tr = (s, n) => { s = String(s ?? ''); return s.length > n ? s.slice(0, n - 1) + '…' : s; };
const pct = (x) => (100 * x).toFixed(2);
const MS = { M1: 1, M2: 2, M3: 3, M4: 4, M5: 5, OOS: 9 };
function evLink(ev) {
  const m = String(ev).match(/^([\w./@-]+\.[\w]+)(?::(\d+)(?:-(\d+))?)?/);
  if (!m || !fs.existsSync(path.join(ROOT, m[1]))) return esc(tr(ev, 60));
  const anchor = m[2] && !m[1].endsWith('.md') ? `#L${m[2]}${m[3] ? '-L' + m[3] : ''}` : '';
  return `[${path.basename(m[1])}${m[2] ? ':' + m[2] + (m[3] ? '-' + m[3] : '') : ''}](../../../${m[1]}${anchor})`;
}
const capCell = (id) => { const c = caps[id]; return c ? `[${id}](../${c.doc})` : esc(id); };
const todayCell = (id, n = 90) => { const c = caps[id]; if (!c) return ''; const ev = (c.evidence || []).slice(0, 1).map(evLink).join(' '); return `${esc(tr(c.today, n))}${ev ? ' ' + ev : ''}`; };
const useCells = (u) => (u ? `${u.n} / ${u.cs} / ${pct(u.all)} / ${pct(u.in)} / ${esc(top3(u.ids))}` : '0 / 0 / 0.00 / 0.00 / -');
function mkUse(ids, cs) { ids = new Set(ids); return { n: ids.size, cs, all: wAll(ids), in: wIn(ids), ids }; }
const USEH = '#ext / sites / w% all / w% E_in / top 3';
function writeSplit(base, title, intro, tableHead, rows, extraTail = []) {
  // index + parts when needed; returns list of files written
  const head = HDR(title).concat(intro);
  const budget = MAX - 8;
  if (head.length + tableHead.length + rows.length + extraTail.length <= budget) {
    fs.writeFileSync(path.join(OUT, base + '.md'), head.concat(tableHead, rows, [''], extraTail).join('\n') + '\n');
    return [base + '.md'];
  }
  const per = budget - HDR('').length - tableHead.length - 2;
  const parts = [];
  for (let i = 0; i < rows.length; i += per) parts.push(rows.slice(i, i + per));
  parts.forEach((p, i) => fs.writeFileSync(path.join(OUT, `${base}-${i + 1}.md`), HDR(`${title} (part ${i + 1} of ${parts.length})`).concat([`Index: [${base}.md](${base}.md).`, ''], tableHead, p).join('\n') + '\n'));
  const links = parts.map((p, i) => `- [${base}-${i + 1}.md](${base}-${i + 1}.md): rows ${i * per + 1}-${i * per + p.length}`);
  fs.writeFileSync(path.join(OUT, base + '.md'), head.concat(['## Parts', ...links, ''], extraTail).join('\n') + '\n');
  return [base + '.md', ...parts.map((_, i) => `${base}-${i + 1}.md`)];
}

// ---------- API ----------
const stable = new Map(vApi.items.map((i) => [i.id, i]));
const forkRe = rules.find(([, c]) => c === 'fork.api')?.[0];
const ruleCap = (id) => rules.find(([re]) => re.test(id))[1];
function normApi(id) {
  let x = id.startsWith('default.') ? id.slice(8) : id;
  if (!stable.has(x) && x.includes('.')) { const b = x.split('.')[0]; if (stable.has(b) && !stable.get(b).kind.startsWith('namespace')) x = b; }
  if (!stable.has(x)) {
    if (/^[A-Z][A-Z0-9_]*$/.test(x)) return null;
    if (/^[a-z][A-Za-z0-9]*$/.test(x) && !(forkRe && forkRe.test(x))) return null;
  }
  let cap = ruleCap(x);
  if (!stable.has(x) && caps[cap]?.track === 'in') cap = 'proposed.api';
  return { id: x, stable: stable.has(x), cap };
}
const apiRows = new Map(); const noise = [];
for (const it of vApi.items) apiRows.set(it.id, { id: it.id, kind: it.kind, desc: it.docFirstSentence || '', src: `vscode.d.ts:${it.line}`, cap: normApi(it.id).cap, ids: new Set(), cs: 0, stable: true });
for (const [id, u] of Object.entries(usage.api)) {
  const n = normApi(id);
  if (!n) { noise.push(`${id} (${u.count})`); continue; }
  if (!apiRows.has(n.id)) apiRows.set(n.id, { id: n.id, kind: 'non-stable', desc: 'not declared in stable vscode.d.ts', src: '-', cap: n.cap, ids: new Set(), cs: 0, stable: false });
  const r = apiRows.get(n.id); u.extensions.forEach((e) => r.ids.add(e)); r.cs += u.callSites; if (n.id !== id) r.folded = (r.folded || []).concat(id);
}
for (const r of apiRows.values()) r.use = r.ids.size ? mkUse(r.ids, r.cs) : null;
const byPrio = (a, b) => (b.use?.in || 0) - (a.use?.in || 0) || (b.use?.n || 0) - (a.use?.n || 0) || a.id.localeCompare(b.id);
const apiRow = (r) => { const c = caps[r.cap] || {}; return `| \`${esc(r.id)}\`${r.folded ? ' (+' + r.folded.length + ' folded)' : ''} | ${r.kind} | ${esc(tr(r.desc, 90))} ${r.src} | ${capCell(r.cap)}: ${todayCell(r.cap, 70)} | ${c.gap} | ${useCells(r.use)} | ${pct(r.use?.in || 0)} | ${esc(tr(c.change, 60))} | ${c.effort}/${c.risk} | ${(c.wp || []).join(', ')} | ${c.milestone} |`; };
const API_TH = [`| id | kind | VS Code | easyIDE today (capability) | gap | ${USEH} | prio | change | E/R | WP | ms |`, '|---|---|---|---|---|---|---|---|---|---|---|'];
const stableRows = [...apiRows.values()].filter((r) => r.stable).sort(byPrio);
const nonStable = [...apiRows.values()].filter((r) => !r.stable).sort(byPrio);
// per-capability summary
const capUse = {};
const addCapUse = (cap, ids) => { (capUse[cap] ??= new Set()); ids.forEach((i) => capUse[cap].add(i)); };
for (const r of apiRows.values()) if (r.ids.size) addCapUse(r.cap, r.ids);
const gapCount = (rows, f) => rows.reduce((o, r) => { const g = f(r); o[g] = (o[g] || 0) + 1; return o; }, {});
const gapLine = (o) => Object.keys(o).sort().map((k) => `${k} ${o[k]}`).join(' · ');
const apiCapIds = [...new Set([...apiRows.values()].map((r) => r.cap))].sort();
const capSummary = apiCapIds.map((c) => ({ c, n: [...apiRows.values()].filter((r) => r.cap === c).length, u: [...apiRows.values()].filter((r) => r.cap === c && r.ids.size).length, use: capUse[c] ? mkUse(capUse[c], 0) : null })).sort((a, b) => (b.use?.in || 0) - (a.use?.in || 0) || a.c.localeCompare(b.c));
const apiIntro = [
  `Stable API ids: ${stableRows.length} (all of vscode.d.ts, one row per top-level declaration or namespace member); corpus ids not in stable vscode.d.ts: ${nonStable.length} (section below); extractor noise dropped: ${noise.length}.`,
  `Rows by gap class (stable): ${gapLine(gapCount(stableRows, (r) => caps[r.cap].gap))}. Used by the corpus: ${stableRows.filter((r) => r.ids.size).length}.`,
  'Columns: use = #extensions / call sites / weight share over all corpus / over E_in / top 3 by downloads; prio = w% E_in. ms = milestone (D11).', '',
  '## Summary per capability (API rows only)', '', '| capability | track | gap | #ids | #used | w% E_in (union) | effort | WP | ms |', '|---|---|---|---|---|---|---|---|---|',
  ...capSummary.map(({ c, n, u, use }) => `| ${capCell(c)} | ${caps[c].track} | ${caps[c].gap} | ${n} | ${u} | ${pct(use?.in || 0)} | ${caps[c].effort} | ${caps[c].wp.join(', ')} | ${caps[c].milestone} |`), ''];
const apiTail = ['## Ids used by the corpus but not in stable vscode.d.ts (proposed / fork / removed)', '', ...API_TH, ...nonStable.map(apiRow), '', '## Dropped as extractor noise', '', esc(noise.sort().join(', ')), ''];
const files = [];
files.push(...writeSplit('api', 'VS Code API matrix', apiIntro, API_TH, stableRows.map(apiRow), apiTail));

// ---------- contributes ----------
const conRows = [];
const allPoints = { ...Object.fromEntries(Object.entries(mCon.points).map(([k, v]) => [k, { ...v, v: vCon.items.find((i) => i.point === k) }])), ...mCon.corpusOnly };
for (const [p, m] of Object.entries(allPoints)) {
  const u = usage.contributes[p]; const use = u ? mkUse(u.extensions, u.callSites) : null;
  conRows.push({ id: p, use, line: `| \`${esc(p)}\` | ${m.v ? (m.v.registered ? 'registered' : 'doc-only') + (m.v.proposalChecksInFile?.length ? ', proposal-gated' : '') : 'corpus-only'} | ${esc(tr(m.v?.description || m.source || '', 70))} ${m.v?.ref || ''} | ${capCell(m.capability)} | ${m.ourStatus ? m.ourStatus + ' ' + (m.evidence || []).slice(0, 1).map(evLink).join('') : esc(tr(caps[m.capability]?.today, 60))} | ${m.gap} | ${useCells(use)} | ${pct(use?.in || 0)} | ${esc(tr(m.change, 80))} | ${m.effort}/${m.risk} | ${m.wp.join(', ')} | ${m.milestone} |` });
  if (use) addCapUse(m.capability, use.ids);
}
conRows.sort(byPrio);
files.push(...writeSplit('contributes', 'Contribution points matrix', [`${Object.keys(mCon.points).length} VS Code contribution points + ${Object.keys(mCon.corpusOnly).length} corpus-only keys. Gap: ${gapLine(gapCount(Object.values(allPoints), (m) => m.gap))}. Every .vsix point also needs [ext.manifest](../${caps['ext.manifest'].doc}) (M1).`, ''],
  [`| point | kind | VS Code | capability | easyIDE today | gap | ${USEH} | prio | change | E/R | WP | ms |`, '|---|---|---|---|---|---|---|---|---|---|---|---|'], conRows.map((r) => r.line)));

// ---------- activation events ----------
const actRows = Object.entries(mAct).map(([ev, m]) => {
  const k = ev.replace(/:$/, ''); const v = vAct.items.find((i) => i.event === ev);
  const ids = new Set([...(usage.activationEvents[k]?.extensions || []), ...(usage.implicitActivationEvents[k]?.extensions || [])]);
  const use = ids.size ? mkUse(ids, (usage.activationEvents[k]?.callSites || 0) + (usage.implicitActivationEvents[k]?.callSites || 0)) : null;
  return { id: ev, use, line: `| \`${esc(ev)}\` | ${m.implicit ? 'implicit' : ''} | ${esc(tr(v?.schemaDescription || '', 70))} ${v?.sourceRefs?.[0] || ''} | ${capCell(m.capability)} | ${m.ourStatus ? m.ourStatus + ' (WASM/.easyext) ' + (m.evidence || []).slice(0, 1).map(evLink).join('') : ''} | ${m.gap} | ${usage.activationEvents[k]?.count || 0} decl / ${usage.implicitActivationEvents[k]?.count || 0} impl; ${useCells(use)} | ${pct(use?.in || 0)} | ${esc(tr(m.change, 70))} | ${m.effort}/${m.risk} | ${m.wp.join(', ')} | ${m.milestone} |` };
}).sort(byPrio);
files.push(...writeSplit('activation-events', 'Activation events matrix', [`${actRows.length} events. Gap: ${gapLine(gapCount(Object.values(mAct), (m) => m.gap))}. Use counts declared + implicit (from contributions) together.`, ''],
  [`| event | kind | VS Code | capability | easyIDE today | gap | use (${USEH}) | prio | change | E/R | WP | ms |`, '|---|---|---|---|---|---|---|---|---|---|---|---|'], actRows.map((r) => r.line)));

// ---------- menus ----------
const menuRows = Object.entries(mMenu.locations).map(([loc, m]) => {
  const u = usage.menus[loc]; const use = u ? mkUse(u.extensions, u.callSites) : null; const v = vMenu.items.find((i) => i.key === loc);
  if (use && m.track === 'in') addCapUse(m.capability, use.ids);
  return { id: loc, use, line: `| \`${esc(loc)}\` | ${m.proposed || (m.own ? 'easyIDE-own' : '')} | ${esc(tr(v?.description || '', 60))} ${v?.ref || ''} | ${capCell(m.capability)} (${m.track}) | ${m.ourStatus || '-'}: ${esc(tr(m.note, 60))} ${(m.evidence || []).slice(0, 1).map(evLink).join('')} | ${m.gap} | ${useCells(use)} | ${pct(use?.in || 0)} | ${m.wp.join(', ')} | ${m.milestone} |` };
}).sort(byPrio);
const subRows = Object.entries(usage.menus).filter(([k]) => !mMenu.locations[k]).map(([k, u]) => ({ id: k, use: mkUse(u.extensions, u.callSites) })).sort(byPrio);
files.push(...writeSplit('menus', 'Menu locations matrix', [`${menuRows.length} locations (VS Code apiMenus + easyIDE-own). Gap: ${gapLine(gapCount(Object.values(mMenu.locations), (m) => m.gap))}. Corpus menu keys that are not locations (submenu ids): ${subRows.length}, rule: ${mMenu.corpusOnlyRule.capability} ${mMenu.corpusOnlyRule.milestone}.`, ''],
  [`| location | proposal | VS Code | capability (track) | easyIDE today | gap | ${USEH} | prio | WP | ms |`, '|---|---|---|---|---|---|---|---|---|---|'], menuRows.map((r) => r.line),
  ['## Corpus-only menu keys (extension submenu ids)', '', `| key | ${USEH} |`, '|---|---|', ...subRows.map((r) => `| \`${esc(r.id)}\` | ${useCells(r.use)} |`)]));

// ---------- when context ----------
const vKeys = new Map(vWhen.items.map((i) => [i.name, i]));
function whenRule(k) {
  const inVs = vKeys.has(k), used = !!usage.whenKeys[k];
  for (const r of mWhen) {
    if (r.match === 'exact' && r.pattern === k) return r;
    if (r.match === 'prefix' && k.startsWith(r.pattern)) return r;
    if (r.match === 'regex' && new RegExp(r.pattern).test(k)) return r;
  }
  return mWhen.find((r) => r.match === (inVs ? (used ? 'vscode-default' : 'vscode-unused') : 'extension-default'));
}
const wRow = (k) => { const r = whenRule(k); const v = vKeys.get(k); const u = usage.whenKeys[k]; const use = u ? mkUse(u.extensions, u.callSites) : null;
  return { id: k, use, r, line: `| \`${esc(k)}\` | ${esc(tr(v?.docDescription || v?.description || (v ? '' : 'not declared by VS Code'), 60))} ${v?.declarations?.[0]?.ref || ''} | ${capCell(r.capability)} | ${r.who} | ${r.gap} | ${useCells(use)} | ${r.milestone} |` }; };
const WTH = [`| key | VS Code | capability | who sets it | gap | ${USEH} | ms |`, '|---|---|---|---|---|---|---|'];
const vsRef = [...vKeys.keys()].filter((k) => usage.whenKeys[k] || vKeys.get(k).documented).map(wRow).sort(byPrio);
const extRef = Object.keys(usage.whenKeys).filter((k) => !vKeys.has(k)).map(wRow).sort(byPrio);
const srcOnly = [...vKeys.keys()].filter((k) => !usage.whenKeys[k] && !vKeys.get(k).documented).sort().map((k) => { const r = whenRule(k); const v = vKeys.get(k); return `| \`${esc(k)}\` | ${v.type || ''} | ${v.declarations?.[0]?.ref || ''} | ${r.capability} | ${r.gap} |`; });
const allW = [...vsRef, ...extRef];
const opRows = vWhen.operators.operators.map((o) => `| ${o.tokenType} | ${o.lexemes.map((l) => '`' + esc(l) + '`').join(' ')} | ${esc(o.meaning)} | ${o.parserRef} |`);
const f1 = writeSplit('when-context-corpus', 'When-clause keys used by the corpus but not declared by VS Code', [`${extRef.length} extension-owned keys (set by extensions via setContext) or config.* keys.`, ''], WTH, extRef.map((r) => r.line));
const f2 = writeSplit('when-context-all', 'VS Code context keys with no corpus use and no documentation', [`${srcOnly.length} keys declared in VS Code source only. Default rule: ${whenRule('zzzNoSuchKeyInVs') && 'see when.json vscode-unused'} (Not-planned unless the corpus starts using them).`, ''], ['| key | type | declared at | capability | gap |', '|---|---|---|---|---|'], srcOnly);
files.push(...f1, ...f2);
files.push(...writeSplit('when-context', 'When-clause context matrix', [
  `VS Code declares ${vWhen.items.length} keys (${vWhen.meta.summary.documented} documented); the corpus references ${Object.keys(usage.whenKeys).length} keys (${vsRef.filter((r) => usage.whenKeys[r.id]).length} VS Code keys, ${extRef.length} extension-owned). Rules: tools/vsx-audit/mapping/when.json. Gap over corpus keys: ${gapLine(gapCount(allW.filter((r) => r.use), (r) => r.r.gap))}.`,
  `Other files: [when-context-corpus.md](when-context-corpus.md) (extension-owned keys), [when-context-all.md](when-context-all.md) (source-only keys).`, '',
  '## Operators (VS Code scanner/parser)', '', '| token | lexemes | meaning | parser |', '|---|---|---|---|', ...opRows, '',
  '## VS Code keys referenced by the corpus or documented', ''], WTH, vsRef.map((r) => r.line)));

// ---------- shapes ----------
const shRows = Object.entries(mShape).map(([n, s]) => { const v = vShape.items.find((i) => i.name === n); return { n, s, line: `| ${n} | ${s.side} | ${s.methods} | ${v?.ref || ''} | ${s.disposition} | ${s.milestone} | ${s.wp.join(', ')} | ${esc(tr(s.counterpart || s.notes || '', 90))} |` }; })
  .sort((a, b) => a.s.side.localeCompare(b.s.side) || (MS[a.s.milestone] || 9) - (MS[b.s.milestone] || 9) || a.n.localeCompare(b.n));
files.push(...writeSplit('extHost-shapes', 'Extension-host RPC shapes matrix', [`${shRows.length} shapes. MainThread dispositions from design.md §6: ${gapLine(gapCount(Object.values(mShape).filter((s) => s.side === 'MainThread'), (s) => s.disposition))}. ExtHost shapes run unmodified in the vendored host.`, ''],
  ['| shape | side | methods | VS Code | disposition | ms | WP | counterpart / notes |', '|---|---|---|---|---|---|---|---|'], shRows.map((r) => r.line)));

// ---------- milestone coverage ----------
const pointMap = (p) => mCon.points[p] || mCon.corpusOnly[p] || { capability: 'ext.api', milestone: 'M1' };
const menuMap = (l) => mMenu.locations[l] || mMenu.corpusOnlyRule;
const cov = [];
const capStats = {};
const trackW = {};
for (const e of corpus.extensions) {
  const items = [{ k: 'base', id: 'host', cap: 'host.process', ms: 'M1', track: 'in' }, { k: 'base', id: 'manifest', cap: 'ext.manifest', ms: 'M1', track: 'in' }];
  for (const id of Object.keys(e.apiUsage || {})) { const n = normApi(id); if (n) items.push({ k: 'api', id: n.id, cap: n.cap, ms: caps[n.cap].milestone, track: caps[n.cap].track }); }
  for (const p of Object.keys(e.contributes || {})) { const m = pointMap(p); items.push({ k: 'contrib', id: p, cap: m.capability, ms: m.milestone, track: caps[m.capability].track }); }
  for (const l of Object.keys(e.menus || {})) { const m = menuMap(l); items.push({ k: 'menu', id: l, cap: m.capability, ms: m.milestone, track: m.track ?? caps[m.capability].track }); }
  const inItems = items.filter((i) => i.track === 'in');
  const tracks = [...new Set(items.filter((i) => i.track !== 'in').map((i) => i.track))].sort();
  for (const t of tracks) (trackW[t] ??= new Set()).add(e.id);
  const max = Math.max(...inItems.map((i) => MS[i.ms] ?? 9));
  const block = [...new Set(inItems.filter((i) => (MS[i.ms] ?? 9) === max).map((i) => i.cap))].sort();
  const cls = classify(e);
  cov.push({ id: e.id, w: e.downloadCount, cls, ms: max >= 9 ? 'never' : 'M' + max, block, blockItems: inItems.filter((i) => (MS[i.ms] ?? 9) === max).map((i) => `${i.k}:${i.id}`).sort(), tracks });
  if (cls === 'in') for (const c of new Set(inItems.map((i) => i.cap))) { const s = (capStats[c] ??= { use: 0, crit: 0, sole: 0, n: 0 }); s.use += e.downloadCount; s.n++; if (block.includes(c)) { s.crit += e.downloadCount; if (block.length === 1) s.sole += e.downloadCount; } }
}
cov.sort((a, b) => b.w - a.w || a.id.localeCompare(b.id));
const score = {};
for (const k of [1, 2, 3, 4, 5]) { const w = cov.filter((c) => c.cls === 'in' && c.ms !== 'never' && MS[c.ms] <= k).reduce((s, c) => s + c.w, 0); score['M' + k] = { S_in: +(w / TOTAL_IN).toFixed(4), S_all: +(w / TOTAL).toFixed(4), extensions: cov.filter((c) => c.cls === 'in' && c.ms !== 'never' && MS[c.ms] <= k).length }; }
const never = cov.filter((c) => c.cls === 'in' && c.ms === 'never');
// declarative today
const inPts = (e) => Object.keys(e.contributes || {}).filter((p) => caps[pointMap(p).capability].track === 'in');
const strictIds = corpus.extensions.filter((e) => EIN.has(e.id) && inPts(e).length && inPts(e).every((p) => p === 'iconThemes')).map((e) => e.id);
const engineIds = corpus.extensions.filter((e) => EIN.has(e.id) && inPts(e).length && inPts(e).every((p) => pointMap(p).gap === 'Have')).map((e) => e.id);
const covRows = cov.map((c) => `| ${c.id} | ${pct(c.w / TOTAL)} | ${c.cls} | ${c.cls === 'in' ? c.ms : '-'} | ${esc(tr(c.block.join(', '), 90))} | ${esc(tr(c.blockItems.join(', '), 110))} | ${c.tracks.join(' ')} |`);
const scoreLines = ['| milestone | E_in extensions covered | S_in upper bound | S_all upper bound |', '|---|---|---|---|', ...Object.entries(score).map(([k, v]) => `| ${k} | ${v.extensions} | ${pct(v.S_in)}% | ${pct(v.S_all)}% |`), `| never (<= M5) | ${never.length} | ${pct(never.reduce((s, c) => s + c.w, 0) / TOTAL_IN)}% of E_in | |`, ''];
files.push(...writeSplit('milestone-coverage', 'Per-extension earliest milestone', [
  `E_in ${EIN.size} extensions (${pct(TOTAL_IN / TOTAL)}% of corpus weight). Earliest milestone = latest milestone among the in-scope items the extension uses (API capabilities, contribution points, menu locations; host + manifest at M1). OOS-track items are excluded (listed in the last column). Gate g4 scenarios and bugs are not modelled: upper bounds.`, '', ...scoreLines], ['| extension | w% | class | earliest | blocking capabilities | blocking items | OOS tracks touched |', '|---|---|---|---|---|---|---|'], covRows));

// ---------- summary json ----------
const topBlockers = Object.entries(capStats).map(([c, s]) => ({ capability: c, gap: caps[c].gap, milestone: caps[c].milestone, effort: caps[c].effort, wp: caps[c].wp, extensions: s.n, useW_in: +(s.use / TOTAL_IN).toFixed(4), criticalW_in: +(s.crit / TOTAL_IN).toFixed(4), soleW_in: +(s.sole / TOTAL_IN).toFixed(4) }))
  .sort((a, b) => b.useW_in - a.useW_in || b.criticalW_in - a.criticalW_in || a.capability.localeCompare(b.capability));
const summary = {
  generatedBy: 'tools/vsx-audit/build-matrix.mjs', snapshotAt: corpus.meta.snapshotAt, scanVersion: corpus.meta.scanVersion, vscode: vApi.meta.vscodeVersion,
  corpus: { extensions: corpus.extensions.length, E_in: EIN.size, E_in_weightShare: +(TOTAL_IN / TOTAL).toFixed(4) },
  gapCounts: { capabilities: gapCount(Object.values(caps), (c) => c.gap), apiStable: gapCount(stableRows, (r) => caps[r.cap].gap), apiStableUsed: gapCount(stableRows.filter((r) => r.ids.size), (r) => caps[r.cap].gap), contributes: gapCount(Object.values(allPoints), (m) => m.gap), activation: gapCount(Object.values(mAct), (m) => m.gap), menus: gapCount(Object.values(mMenu.locations), (m) => m.gap), whenCorpusKeys: gapCount(allW.filter((r) => r.use), (r) => r.r.gap) },
  rows: { apiStable: stableRows.length, apiNonStable: nonStable.length, apiNoise: noise.length, contributes: Object.keys(allPoints).length, activation: actRows.length, menus: menuRows.length, whenVsReferenced: vsRef.length, whenExtension: extRef.length, whenSourceOnly: srcOnly.length, shapes: shRows.length },
  today: { codeExtensions: { S_in: 0, S_all: 0, note: 'no extension host exists: g1/g3 fail for every code extension' },
    declarativeStrict: { extensions: strictIds, g2ShareOfEin: +(wIn(strictIds)).toFixed(4), S_in_contribution: +(wIn(strictIds) / 4).toFixed(4), note: 'raw .vsix accepts only iconThemes today' },
    declarativeEngine: { extensions: engineIds.length, g2ShareOfEin: +(wIn(engineIds)).toFixed(4), S_in_contribution: +(wIn(engineIds) / 4).toFixed(4), note: 'all in-scope points have an engine (gap Have) once ext.manifest lands' } },
  projected: score, never: never.map((c) => ({ id: c.id, w_in: +(c.w / TOTAL_IN).toFixed(4), blocking: c.blockItems })),
  tracks: Object.fromEntries(Object.entries(trackW).sort().map(([t, s]) => [t, { extensions: s.size, weightShareAll: +wAll(s).toFixed(4), weightShareEin: +wIn(s).toFixed(4) }])),
  topBlockers: topBlockers.slice(0, 40), files: files.sort(),
};
fs.writeFileSync(path.join(DATA, 'matrix-summary.json'), JSON.stringify(summary, null, 1) + '\n');
for (const f of files) { const n = fs.readFileSync(path.join(OUT, f), 'utf8').split('\n').length - 1; if (n > MAX) throw new Error(`${f} has ${n} lines`); }
console.log(`wrote ${files.length} matrix files + data/matrix-summary.json`);
